package config

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// Version is set at build time via ldflags.
var Version = "dev"

const (
	DefaultConfigFilename      = "genxcode.yaml"
	DefaultTemplateName        = "pytorch"
	DefaultTemplateManifest    = "template.yaml"
	DefaultTemplateConfig      = "genxcode.yaml"
	DefaultTemplateFilesDir    = "files"
	MissingTemplateError       = "template is required in genxcode.yaml. Run `genxcode init <template>` or add a `template:` field."
)

// TemplateSpec represents metadata about a template.
type TemplateSpec struct {
	Name                 string   `yaml:"name"`
	Description          string   `yaml:"description"`
	Aliases              []string `yaml:"aliases"`
	DefaultConfigFilename string  `yaml:"default_config"`
	FilesDirname         string   `yaml:"files_dir"`
	ApplyHint            string   `yaml:"apply_hint"`
}

// GenerationConfig is the user-provided genxcode.yaml.
type GenerationConfig struct {
	Template string                 `yaml:"template"`
	Name     string                 `yaml:"name"`
	Data     map[string]interface{} `yaml:",inline"`
}

// NormalizeTemplateName lowercases and strips separators.
func NormalizeTemplateName(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	value = strings.ReplaceAll(value, "-", "")
	value = strings.ReplaceAll(value, "_", "")
	return value
}

// LoadTemplateSpec reads template.yaml from a directory.
func LoadTemplateSpec(manifestPath string) (*TemplateSpec, error) {
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}
	var spec TemplateSpec
	if err := yaml.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}
	if spec.DefaultConfigFilename == "" {
		spec.DefaultConfigFilename = DefaultTemplateConfig
	}
	if spec.FilesDirname == "" {
		spec.FilesDirname = DefaultTemplateFilesDir
	}
	if spec.Name == "" {
		spec.Name = "unknown"
	}
	return &spec, nil
}

// LoadConfig reads genxcode.yaml from disk.
func LoadConfig(path string) (*GenerationConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("config file not found: %s", path)
		}
		return nil, err
	}

	var raw map[string]interface{}
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	tmpl, ok := raw["template"].(string)
	if !ok || strings.TrimSpace(tmpl) == "" {
		return nil, fmt.Errorf(MissingTemplateError)
	}

	name, _ := raw["name"].(string)
	if strings.TrimSpace(name) == "" {
		name = tmpl
	}

	return &GenerationConfig{
		Template: strings.TrimSpace(tmpl),
		Name:     strings.TrimSpace(name),
		Data:     raw,
	}, nil
}

// ParseYAML unmarshals YAML data into a destination.
func ParseYAML(data []byte, dest interface{}) error {
	return yaml.Unmarshal(data, dest)
}

// WriteDefaultConfig writes a genxcode.yaml from a template's default config.
func WriteDefaultConfig(dest, templateName, defaultConfigPath string, force bool) error {
	if _, err := os.Stat(dest); err == nil && !force {
		return fmt.Errorf("%s already exists. Use --force to overwrite it", dest)
	}
	data, err := os.ReadFile(defaultConfigPath)
	if err != nil {
		return fmt.Errorf("read default config: %w", err)
	}
	content := fmt.Sprintf("# Generated by `genxcode init %s`\n%s", templateName, string(data))
	if err := os.WriteFile(dest, []byte(content), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}
